In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
df = pd.read_csv("road_network.csv")
df.head()

,road_id,road_name,road_type,length_km,lanes,speed_limit_kmh,capacity_vehicles_per_hour,has_bus_lane,has_bike_lane,surface_condition,last_maintenance_date,latitude_start,longitude_start,latitude_end,longitude_end,district,toll_rate_rp,avg_daily_traffic
0,RD-0001,Jl. Segment 1,Jalan Kolektor,4.3,4,60,5384,0,0,Cukup,21-12-2022,-6.173938,106.920654,-6.187271,106.937674,PIK,0,10833
1,RD-0002,Jl. Segment 2,Jalan Arteri,4.3,4,80,6132,0,0,Baik,17-11-2022,-6.248396,106.768647,-6.246220,106.771962,Depok,0,6921
2,RD-0003,Jl. Segment 3,Jalan Lokal,1.8,2,40,978,0,0,Cukup,15-04-2023,-6.267631,106.814963,-6.264098,106.831007,Tangerang,0,1085
3,RD-0004,Jl. Segment 4,Jalan Kolektor,1.8,4,60,4160,0,1,Rusak Berat,17-05-2022,-6.112216,106.954036,-6.122268,106.958261,Mangga Dua,0,6145
4,RD-0005,Jl. Segment 5,Jalan Tol,22.7,4,80,6600,1,0,Baik,16-02-2024,-6.349760,106.861835,-6.341074,106.856648,Sudirman,7000,8023

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   road_id                     200 non-null    str
 1   road_name                   200 non-null    str
 2   road_type                   200 non-null    str
 3   length_km                   200 non-null    float64
 4   lanes                       200 non-null    int64
 5   speed_limit_kmh             200 non-null    int64
 6   capacity_vehicles_per_hour  200 non-null    int64
 7   has_bus_lane                200 non-null    int64
 8   has_bike_lane               200 non-null    int64
 9   surface_condition           200 non-null    str
 10  last_maintenance_date       200 non-null    str
 11  latitude_start              200 non-null    float64
 12  longitude_start             200 non-null    float64
 13  latitude_end                200 non-null    float64
 14  longitude_end               200 non-null    float64
 15  district                    200 non-null    str
 16  toll_rate_rp                200 non-null    int64
 17  avg_daily_traffic           200 non-null    int64
dtypes: float64(5), int64(7), str(6)
memory usage: 28.3 KB

In [4]:
df.isnull().sum()

road_id                       0
road_name                     0
road_type                     0
length_km                     0
lanes                         0
speed_limit_kmh               0
capacity_vehicles_per_hour    0
has_bus_lane                  0
has_bike_lane                 0
surface_condition             0
last_maintenance_date         0
latitude_start                0
longitude_start               0
latitude_end                  0
longitude_end                 0
district                      0
toll_rate_rp                  0
avg_daily_traffic             0
dtype: int64

In [6]:
df.shape

(200, 18)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

,length_km,lanes,speed_limit_kmh,capacity_vehicles_per_hour,has_bus_lane,has_bike_lane,latitude_start,longitude_start,latitude_end,longitude_end,toll_rate_rp,avg_daily_traffic
count,200.00000,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,5.99450,3.335000,57.200000,4559.49000,0.190000,0.395000,-6.222513,106.858006,-6.221939,106.859040,3050.000000,5497.510000
std,6.07204,2.089162,29.161825,4157.73614,0.393285,0.490077,0.071297,0.082616,0.073120,0.082277,6461.910043,5264.646678
min,0.30000,1.000000,20.000000,404.00000,0.000000,0.000000,-6.349760,106.703131,-6.363767,106.692182,0.000000,353.000000
25%,1.90000,2.000000,40.000000,982.50000,0.000000,0.000000,-6.275835,106.792370,-6.278966,106.794568,0.000000,1167.750000
50%,3.05000,3.000000,50.000000,3112.00000,0.000000,0.000000,-6.227666,106.862516,-6.221347,106.864975,0.000000,3675.000000
75%,8.35000,4.000000,80.000000,6765.00000,0.000000,1.000000,-6.159397,106.922157,-6.163668,106.921874,0.000000,8847.250000
max,24.10000,8.000000,120.000000,15976.00000,1.000000,1.000000,-6.101649,106.998380,-6.087672,107.011265,25000.000000,28394.000000

In [9]:
df["avg_daily_traffic"].describe()

count      200.000000
mean      5497.510000
std       5264.646678
min        353.000000
25%       1167.750000
50%       3675.000000
75%       8847.250000
max      28394.000000
Name: avg_daily_traffic, dtype: float64

In [12]:
x = df[[
    "length_km",
    "lanes",
    "speed_limit_kmh",
    "capacity_vehicles_per_hour",
    "has_bus_lane",
    "has_bike_lane",
    "toll_rate_rp"
]]

y = df["avg_daily_traffic"]

In [13]:
x.head()

,length_km,lanes,speed_limit_kmh,capacity_vehicles_per_hour,has_bus_lane,has_bike_lane,toll_rate_rp
0,4.3,4,60,5384,0,0,0
1,4.3,4,80,6132,0,0,0
2,1.8,2,40,978,0,0,0
3,1.8,4,60,4160,0,1,0
4,22.7,4,80,6600,1,0,7000

In [14]:
y.head()

0    10833
1     6921
2     1085
3     6145
4     8023
Name: avg_daily_traffic, dtype: int64

In [15]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [16]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((160, 7), (40, 7), (160,), (40,))

In [17]:
scaler = MinMaxScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [18]:
lr = LinearRegression()

lr.fit(x_train_scaled, y_train)

LinearRegression()

In [19]:
y_pred = lr.predict(x_test_scaled)

y_pred

array([ 5879.95596333,  2685.32492371,  3855.97553324,  6999.84899366,
       18901.77078518,  7066.38148284,  3996.92094514,  1598.01394182,
        7694.7929826 ,  2185.75295574,  8712.52698986,  7547.77554781,
        1108.58755705,  2652.9027211 ,  8726.8698108 ,  2115.9512733 ,
        2102.48683553,   985.33034873,  1189.76040228,  7390.51491188,
       13515.68973466,  2029.53757104, 10087.69745747,  8676.70496034,
        1159.65121418,   857.73010493,  8963.30095133,  3468.3078393 ,
        1141.40377561, 13532.93042824,   831.89194045, 10620.24588528,
         842.86061481,   905.86238195,   744.26086825,  1111.9789115 ,
        1394.83569493,  6297.95189747,  1714.66319153,  7325.45578118])

In [20]:
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 790.8357104764128
MSE: 1507395.6178926968
R2 Score: 0.9175567843686495

In [21]:
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42)
}

for name, model in models.items():
    model.fit(x_train_scaled, y_train)
    y_pred = model.predict(x_test_scaled)

    print(name)
    print("MAE:", mean_absolute_error(y_test, y_pred))
    print("MSE:", mean_squared_error(y_test, y_pred))
    print("R2 Score:", r2_score(y_test, y_pred))
    print("---------------------------")

Linear Regression
MAE: 790.8357104764128
MSE: 1507395.6178926968
R2 Score: 0.9175567843686495
---------------------------
Decision Tree
MAE: 1681.325
MSE: 9790861.025
R2 Score: 0.4645134580999427
---------------------------
Random Forest
MAE: 1132.0627500000003
MSE: 4915658.520652501
R2 Score: 0.7311504089717422
---------------------------

In [23]:
with open("model.pkl", "wb") as f:
    pickle.dump(models["Linear Regression"], f)

with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)